apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfsgwte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yfsgwte
  template:
    metadata:
      labels:
        app: yfsgwte
    spec:
      containers:
      - image: okteto.dev/yfsgwte:latest
        name: yfsgwte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "99af137f-3a11-4df6-9216-c8a37100b991"
        - name: Vless_Path
          value: "/gdfd64fxggeud"
        - name: Vmess_UUID
          value: "99af137f-3a11-4df6-9216-c8a37100b991"
        - name: Vmess_Path
          value: "/gdfd64fxggeud"
        - name: Share_Path
          value: "/v2link"
